name: dosi
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.13
  - numpy>=1.25,<2.0
  - pandas>=2.2,<3.0
  - scikit-learn>=1.4,<1.6
  - scipy>=1.12,<1.15
  - matplotlib>=3.6,<3.9
  - openpyxl>=3.1,<4.0
  - plotly>=6.1,<6.3
  - nbformat>=5.9,<6.0
  - streamlit>=1.45,<2.0