name: dosi
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy==1.26.4
  - pandas==2.2.2
  - pip==24.0.0
  - python==3.11.9
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - matplotlib=3.7.2
  - openpyxl==3.1.5
#  - pip:
#      - -r requirements.txt
